### ISSUE TITLE
Multi-currency support

### ISSUE THREAD

**Issue by xuhcc** [monescript/monescript#2]
Hi @abtechbit !
Are there any plans to support currencies other than USD?

**Comment by abtechbit** [comment]
Hello @xuhcc !

I do not have immediate plans to support alternative currencies. For the time being monescript is meant to be used as a single currency environment. Possible workaround would be to use $ symbol as a placeholder for your home currency (e.g. Euro), and enter alternative currency amounts using conversion rate formula for the transaction date.  The benefit of using $ symbol is that the file can be kept in ASCII format.

Alternatively I will welcome a pull request, supporting seamless use of alternative currency Unicode symbol https://www.unicode.org/charts/PDF/U20A0.pdf .  E.g. if the first transaction in the file is using € sign, all subsequent transaction will need to use that sign as well.

You can also look at https://github.com/monescript/monescript/wiki/Roadmap for the next set of features planned to be implemented for monescript.

Cheers and thank you for the question!
